### ISSUE TITLE
@media \\0 screen {} not working in Safari 7.1 on OSX 10.9 (Mavericks)

### ISSUE THREAD

**Issue by xmo-odoo** [4ae9b8/browserhacks#155]
`@media \\0 screen {}` is described as "Chrome 22-28, Safari >= 7" but in Safari 7.1 (9537.85.10.17.1) on Maverick it doesn't match.

**Comment by atk** [comment]
```
_::-webkit-full-page-media, _:future, :root [selector] { /* seems to work for recent safari */ }
```

**Comment by jeffclayton** [comment]
Yes you are correct, the stats on it are Safari 7.1+ (the full-page-media was one of my originals in case you are wondering)
