### ISSUE TITLE
The text of the "Powered by" section is overlay the image.

### ISSUE THREAD

**Issue by keilovecraft** [4ae9b8/browserhacks#166]
When your resolution is between 1040px and 1080px, I see this error:

 <img width="257" alt="captura de pantalla 2015-09-15 a las 17 52 00" src="https://cloud.githubusercontent.com/assets/3832997/9882022/e34a81d6-5bd2-11e5-88c3-17fe5ecb08c9.png">

**Comment by KittyGiraudel** [comment]
Fixed, thanks.
