### ISSUE TITLE
Failing IE9 CSS-hack

### ISSUE THREAD

**Issue by andreyvolokitin** [4ae9b8/browserhacks#169]
This hack is actually matching in IE9: http://browserhacks.com/#hack-e6b158b7e27bcb157326348efb5c0bb2

**Comment by jeffclayton** [comment]
You are correct - it has something to do with the page DOCTYPE spec as far as I can tell. It does not appear to be standard in the HTML5 spec any more. At least I have found no way to get it to work in recent times.

**Comment by jeffclayton** [comment]
I still have not been able to get this hack to work - would there be any objections if I removed it from the page?

**Comment by KittyGiraudel** [comment]
All good with me.

**Comment by KittyGiraudel** [comment]
Removed. Thanks.
