### ISSUE TITLE
Are all hacks listed as "valid"?

### ISSUE THREAD

**Issue by impressivewebs** [4ae9b8/browserhacks#173]
It seems like all of the hacks listed are categorized as "valid CSS" or "valid JS", etc.... But, for example:

http://browserhacks.com/#hack-ab1bcc7b3a6544c99260f7608f8e845e

Those hacks (which are for IE6-8) are not valid. That is, they will not pass validation, no matter what options are chosen for the validator.

**Comment by jeffclayton** [comment]
Tim are you around? It might be handy to update these. I would be happy to test them if you don't have the time, and give you the results...

**Comment by HugoGiraudel** [comment]
Hey @jeffclayton. I don’t have time to deal with this anymore. Would you like admin repositories over the project to be able to push updates yourself? :)

**Comment by jeffclayton** [comment]
I would be happy to do it.

**Comment by HugoGiraudel** [comment]
I just added you as a collaborator. If anything looks unclear to you, please ask me. :)

**Comment by jeffclayton** [comment]
No problem, and glad to help as always.

**Comment by jeffclayton** [comment]
@impressivewebs I will be updating these and others per testing, thank you for posting. I am also the IT admin at an education company so please bear with me timing-wise. I will get to them as I am able. Your contributions/notifications are very important to us.

**Comment by impressivewebs** [comment]
@jeffclayton That's no problem, this is certainly not an urgent issue. Take your time. I just thought it would be useful for readers to actually be able to see what's valid and what's not. Thanks!

**Comment by jeffclayton** [comment]
I am in full agreement!

**Comment by KittyGiraudel** [comment]
The feature has been removed for now.
