### ISSUE TITLE
Quote authors' images not right

### ISSUE THREAD

**Issue by jacobalvarez** [4ae9b8/browserhacks#175]
At [Browserhacks](http://browserhacks.com/#quotes) the quote authors' images aren't associated with the correct names.  I noticed it with Paul Irish and Christian Heilmann, but I'm unsure about the others.

![peeps](https://cloud.githubusercontent.com/assets/16577341/14462117/3be890dc-008b-11e6-8eaa-8f43af5562c4.jpg)

**Comment by KittyGiraudel** [comment]
Fuck. :D

**Comment by KittyGiraudel** [comment]
Fixed! Thanks. :)

**Comment by jacobalvarez** [comment]
np! :)
