### ISSUE TITLE
Edge version 13 only. Edge version 13 and 14 together.

### ISSUE THREAD

**Issue by mkstix6** [4ae9b8/browserhacks#181]
As far as I've worked out.
(Testing here: http://codepen.io/mkstix6/pen/pRbErK)

@supports (-ms-accelerator: true) {
  // targets Edge Version 13 (but not version 14)
}

@supports (-ms-ime-align: auto) {
  // targets both Edge Version 13 & 14
}

I was testing using Browserstack so that's where my version numbers are taken from.

**Comment by jeffclayton** [comment]
noticed those as well - check http://browserstrangeness.bitbucket.org/css_hacks.html#edge to see if we have the same results (my live test page)
