### ISSUE TITLE
JavaScript hack "isSafari" not working on newer Safari.

### ISSUE THREAD

**Issue by frozzare** [4ae9b8/browserhacks#44]
On newer Safari versions `/a/.__proto__` returns `/(?:)/`,  the same for Google Chrome, Firefox and Opera. So doing that check will not tell if it is Safari.

Can't say if this will work on all versions of Safari (tested on 4.0.5 and 6.0.2) and on iOS (3.0, 4.0, 5.1, 6.0).

``` javascript
var isSafari = /Constructor/.test(window.HTMLElement);
```

**Comment by cdumez** [comment]
FYI, /constructor/i.test(window.HTMLElement) will no longer work to detect Safari. You can test the upcoming Safari at: https://developer.apple.com/safari/download/

**Comment by cdumez** [comment]
I filed https://github.com/4ae9b8/browserhacks/issues/172
