### ISSUE TITLE
Add a description to the test page

### ISSUE THREAD

**Issue by TimPietrusky** [4ae9b8/browserhacks#9]
Describe what the green and red background means.

**Comment by dmikester1** [comment]
I don't see anywhere where it says what the green background on the rule means.  Am I missing it?

**Comment by browserstrangeness** [comment]
green means it is working for your browser

**Comment by browserstrangeness** [comment]
...so where you do not see green it is not one that works for your browser.

**Comment by dmikester1** [comment]
awesome, thanks, it'd nice if that was explained on the page

**Comment by browserstrangeness** [comment]
it is sort of an old standard to highlight working hacks, but i do understand. if you check and uncheck the box called 'enable tests' you will see the highlights come and go.
